RegisterCommand('toggleinv', function()
    local focus = not IsNuiFocused()
    SetNuiFocus(focus, focus)
    SetNuiFocusKeepInput(focus)
    SendNUIMessage({ action = focus and 'showInventory' or 'hideInventory' })
end, false)

RegisterKeyMapping('toggleinv', 'Toggle Inventory', 'keyboard', 'F2')

RegisterNUICallback('close', function(_, cb)
    SetNuiFocus(false, false)
    SetNuiFocusKeepInput(false)
    SendNUIMessage({ action = 'hideInventory' })
    cb('ok')
end)
